/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MSGDI (https://sketchfab.com/MSGDI)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/scifi-battlecruiser-liberty-a6ccbd50c3c64e84ba17f6fc869ec7aa
title: Scifi Battlecruiser Liberty
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.ScifiBattlecruiserLibertyHull_002_ScifiBattlecruiserLibertyGrey_0.geometry} material={materials.ScifiBattlecruiserLibertyGrey} />
            <mesh geometry={nodes.ScifiBattlecruiserLibertyHull_002_ScifiSpaceshipStandardWeapons_0.geometry} material={materials.ScifiSpaceshipStandardWeapons} />
            <mesh geometry={nodes.ScifiBattlecruiserLibertyHull_002_ScifiSpaceshipStandardWeapons_0_1.geometry} material={materials.ScifiSpaceshipStandardWeapons} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
